import React from 'react';
import { Sparkles, Smartphone, Stethoscope, ChevronDown, UserCheck, Bot, Globe, Crown, LogOut } from 'lucide-react';
import { Patient, AuthUser } from '../types';

interface HeaderProps {
  patients: Patient[]; selectedPatient: Patient | null; onSelectPatient: (patient: Patient) => void; activeView: string;
  viewMode: 'clinic' | 'patient_portal' | 'super_admin'; onToggleViewMode: (mode: 'clinic' | 'patient_portal' | 'super_admin') => void;
  onOpenCopilot: () => void; onSearchClick: () => void; currentUser?: AuthUser | null; onOpenLandingPage?: () => void; onNavigateToSuperAdmin?: () => void; onLogout?: () => void;
}
export const Header: React.FC<HeaderProps> = ({patients,selectedPatient,onSelectPatient,viewMode,onToggleViewMode,onOpenCopilot,onOpenLandingPage,onNavigateToSuperAdmin,onLogout}) => (
<header className="sticky top-0 z-30 bg-white/95 backdrop-blur-md border-b border-emerald-100 px-4 lg:px-8 py-2.5 shadow-sm"><div className="max-w-7xl mx-auto flex items-center justify-between gap-3">
<div className="flex items-center gap-3"><div onClick={onOpenLandingPage} className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-emerald-600 to-teal-500 flex items-center justify-center text-white font-black text-xl shadow-lg shadow-emerald-600/20 cursor-pointer">🌿</div><div><div className="flex items-center gap-2"><span className="font-black text-lg text-slate-900 tracking-tight">Nutri<span className="text-emerald-600">OS</span></span><span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-emerald-100 text-emerald-800 border border-emerald-200"><Sparkles className="w-3 h-3"/>NutriOS IA Pro</span></div><p className="text-[11px] text-slate-500 hidden sm:block">Prescrição Clínica • Fitoterapia • Gestão SaaS</p></div></div>
<div className="flex items-center gap-2">{viewMode==='clinic'&&<div className="relative"><div className="flex items-center gap-2 bg-emerald-50/60 border border-emerald-200/80 px-3 py-1.5 rounded-xl">{selectedPatient?<><img src={selectedPatient.avatar} alt={selectedPatient.name} className="w-7 h-7 rounded-full object-cover ring-2 ring-emerald-500/40"/><div className="text-left hidden md:block"><p className="text-xs font-bold text-slate-800 leading-tight">{selectedPatient.name}</p><p className="text-[10px] text-emerald-700 font-semibold">{selectedPatient.goal.split('&')[0]} • {selectedPatient.currentBf}% BF</p></div></>:<div className="flex items-center gap-2 text-xs text-slate-500"><UserCheck className="w-4 h-4 text-emerald-600"/><span>Selecionar Paciente</span></div>}<select aria-label="Selecionar Paciente Ativo" value={selectedPatient?.id||''} onChange={e=>{const p=patients.find(x=>x.id===e.target.value);if(p)onSelectPatient(p)}} className="opacity-0 absolute inset-0 w-full h-full cursor-pointer">{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><ChevronDown className="w-4 h-4 text-slate-500 ml-1"/></div></div>}</div>
<div className="flex items-center gap-2"><div className="flex items-center bg-slate-100 p-1 rounded-2xl border border-slate-200">{onNavigateToSuperAdmin&&<button onClick={onNavigateToSuperAdmin} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-black ${viewMode==='super_admin'?'bg-emerald-800 text-white shadow-sm':'text-emerald-950 hover:bg-emerald-50'}`}><Crown className="w-3.5 h-3.5 text-amber-300"/><span className="hidden md:inline">Dono do SaaS</span></button>}<button onClick={()=>onToggleViewMode('clinic')} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold ${viewMode==='clinic'?'bg-white text-emerald-800 shadow-sm':'text-slate-600'}`}><Stethoscope className="w-3.5 h-3.5 text-emerald-600"/><span className="hidden sm:inline">Nutricionista</span></button><button onClick={()=>onToggleViewMode('patient_portal')} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold ${viewMode==='patient_portal'?'bg-white text-teal-800 shadow-sm':'text-slate-600'}`}><Smartphone className="w-3.5 h-3.5 text-teal-600"/><span className="hidden sm:inline">App Paciente</span></button></div><button onClick={onOpenCopilot} className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-black text-xs shadow-md"><Bot className="w-4 h-4"/><span className="hidden sm:inline">Copiloto IA</span></button>{onOpenLandingPage&&<button onClick={onOpenLandingPage} className="flex items-center gap-1 px-3 py-1.5 rounded-xl bg-white border border-emerald-200 text-emerald-900 text-xs font-bold"><Globe className="w-3.5 h-3.5"/><span className="hidden lg:inline">Landing Page</span></button>}{onLogout&&<button onClick={onLogout} className="p-2 rounded-xl text-slate-400 hover:text-rose-600"><LogOut className="w-4 h-4"/></button>}</div>
</div></header>);
