import { useEffect, useMemo, useState } from 'react';
import {
  Activity, CalendarDays, ChevronRight, Crown, Database, Dumbbell, FileText,
  FlaskConical, HeartPulse, Home, Leaf, LogOut, Menu, Search, ShieldCheck,
  Sparkles, Stethoscope, TrendingUp, UserRound, Users, UtensilsCrossed, Wallet,
  X, Calculator, Scale, Bot, RefreshCcw
} from 'lucide-react';

type AnyRow = Record<string, any>;
type View = 'dashboard'|'patients'|'meal'|'workout'|'metabolic'|'anthropometry'|'phyto'|'labs'|'foods'|'appointments'|'financial';

async function api<T=any>(url:string, init:RequestInit={}):Promise<T>{
  const headers=new Headers(init.headers||{});
  if(init.body && !(init.body instanceof FormData) && !headers.has('Content-Type')) headers.set('Content-Type','application/json');
  const r=await fetch(url,{...init,headers,credentials:'same-origin',cache:'no-store'});
  if(r.status===204) return undefined as T;
  const d=await r.json().catch(()=>({}));
  if(!r.ok) throw Object.assign(new Error(d.detail||d.message||`Erro ${r.status}`),{status:r.status});
  return d as T;
}

const pathToView:Record<string,View>={
  '/app':'dashboard','/app/dashboard':'dashboard','/app/pacientes':'patients','/app/planos':'meal','/app/cardapios':'meal',
  '/app/treinos':'workout','/app/metabolico':'metabolic','/app/antropometria':'anthropometry','/app/analise-corporal':'anthropometry',
  '/app/fitoterapia':'phyto','/app/exames':'labs','/app/alimentos':'foods','/app/agenda':'appointments','/app/financeiro':'financial'
};
const viewPath:Record<View,string>={dashboard:'/app',patients:'/app/pacientes',meal:'/app/planos',workout:'/app/treinos',metabolic:'/app/metabolico',anthropometry:'/app/analise-corporal',phyto:'/app/fitoterapia',labs:'/app/exames',foods:'/app/alimentos',appointments:'/app/agenda',financial:'/app/financeiro'};

function Brand(){return <div className="flex items-center gap-3"><div className="h-10 w-10 rounded-2xl bg-emerald-500 flex items-center justify-center shadow-lg shadow-emerald-500/20"><Activity className="w-5 h-5 text-white"/></div><div><div className="font-black tracking-tight text-xl">NutriOS</div><div className="text-[10px] uppercase tracking-[.22em] text-emerald-500 font-bold">Clinical AI</div></div></div>}
function Spinner(){return <div className="min-h-screen bg-slate-950 text-white grid place-items-center"><div className="text-center"><div className="h-10 w-10 rounded-full border-4 border-emerald-500 border-t-transparent animate-spin mx-auto mb-4"/><div className="font-bold text-slate-300">Carregando NutriOS...</div></div></div>}
function Stat({title,value,sub,icon:Icon}:{title:string,value:string|number,sub?:string,icon:any}){return <div className="rounded-3xl bg-white border border-slate-200 p-5 shadow-sm"><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{title}</div><div className="text-3xl font-black mt-2 text-slate-900">{value}</div>{sub&&<div className="text-xs text-slate-500 mt-1">{sub}</div>}</div><div className="h-11 w-11 rounded-2xl bg-emerald-50 text-emerald-600 grid place-items-center"><Icon className="w-5 h-5"/></div></div></div>}

function Landing(){return <div className="min-h-screen bg-slate-950 text-white overflow-hidden"><header className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between"><Brand/><button onClick={()=>location.assign('/login')} className="px-5 py-3 rounded-2xl bg-white text-slate-950 text-sm font-black">Entrar</button></header><main className="max-w-7xl mx-auto px-6 py-16 lg:py-24 grid lg:grid-cols-2 gap-14 items-center"><section><div className="inline-flex gap-2 items-center px-3 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 text-xs font-bold"><Sparkles className="w-4 h-4"/> IA clínica integrada ao fluxo do nutricionista</div><h1 className="mt-6 text-5xl lg:text-7xl font-black tracking-tight leading-[.95]">Gestão clínica.<br/><span className="text-emerald-400">Mais inteligente.</span></h1><p className="mt-6 text-lg text-slate-400 max-w-xl">Pacientes, planos alimentares, antropometria, exames, agenda, financeiro, fitoterapia e inteligência clínica em uma única plataforma.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>location.assign('/login')} className="px-6 py-4 rounded-2xl bg-emerald-500 text-slate-950 font-black">Acessar plataforma</button><button onClick={()=>location.assign('/paciente/login')} className="px-6 py-4 rounded-2xl border border-slate-700 font-black">Portal do paciente</button></div></section><section className="relative"><div className="absolute inset-0 bg-emerald-500/20 blur-[100px] rounded-full"/><div className="relative rounded-[2rem] border border-slate-800 bg-slate-900/80 p-5 shadow-2xl"><div className="grid grid-cols-2 gap-4"><div className="col-span-2 rounded-3xl bg-slate-950 p-6 border border-slate-800"><div className="text-xs text-slate-500 font-bold">VISÃO CLÍNICA</div><div className="mt-2 text-3xl font-black">Tudo que importa, no mesmo painel.</div></div>{['Pacientes','Planos IA','Evolução','Financeiro'].map((x,i)=><div key={x} className="rounded-3xl bg-slate-950 border border-slate-800 p-5"><div className="text-emerald-400 font-black text-2xl">{[24,8,'+12%','R$ 9,8k'][i]}</div><div className="text-sm text-slate-400 mt-1">{x}</div></div>)}</div></div></section></main></div>}

function Login({patient=false}:{patient?:boolean}){
  const [identifier,setIdentifier]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e:any){e.preventDefault();setBusy(true);setError('');try{const d=await api<{redirect?:string}>(patient?'/paciente/auth/login':'/auth/login',{method:'POST',body:JSON.stringify({identifier,password})});location.assign(d.redirect||(patient?'/paciente':'/app'));}catch(e:any){setError(e.message||'Não foi possível entrar');}finally{setBusy(false)}}
  return <div className="min-h-screen bg-slate-950 text-white grid place-items-center px-4"><div className="w-full max-w-md"><div className="mb-7 flex justify-center"><Brand/></div><div className="rounded-[2rem] bg-slate-900 border border-slate-800 p-7 shadow-2xl"><div className="h-12 w-12 rounded-2xl bg-emerald-500/10 text-emerald-400 grid place-items-center mb-5">{patient?<UserRound/>:<Stethoscope/>}</div><h1 className="text-2xl font-black">{patient?'Portal do paciente':'Acesso profissional'}</h1><p className="text-sm text-slate-400 mt-1">Entre com suas credenciais do NutriOS.</p><form onSubmit={submit} className="mt-6 space-y-4"><input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="E-mail ou identificador" className="w-full rounded-2xl bg-slate-950 border border-slate-800 px-4 py-3 outline-none focus:border-emerald-500"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Senha" className="w-full rounded-2xl bg-slate-950 border border-slate-800 px-4 py-3 outline-none focus:border-emerald-500"/>{error&&<div className="text-sm text-red-300 bg-red-500/10 border border-red-500/20 rounded-xl p-3">{error}</div>}<button disabled={busy} className="w-full rounded-2xl bg-emerald-500 text-slate-950 py-3.5 font-black disabled:opacity-60">{busy?'Entrando...':'Entrar'}</button></form><div className="mt-5 flex justify-between text-xs text-slate-500"><button onClick={()=>location.assign('/')}>Voltar ao site</button><button onClick={()=>location.assign(patient?'/login':'/paciente/login')}>{patient?'Sou nutricionista':'Sou paciente'}</button></div></div></div></div>
}

function Sidebar({view,setView,user,onClose}:{view:View,setView:(v:View)=>void,user:any,onClose?:()=>void}){const items:[View,string,any][]=[['dashboard','Visão geral',Home],['patients','Pacientes',Users],['meal','Plano alimentar',UtensilsCrossed],['workout','Treinos',Dumbbell],['metabolic','Metabólico',Calculator],['anthropometry','Análise corporal',Scale],['phyto','Fitoterapia',Leaf],['labs','Exames',FlaskConical],['foods','Base de alimentos',Database],['appointments','Agenda',CalendarDays],['financial','Financeiro',Wallet]];return <aside className="h-full bg-slate-950 text-white p-4 flex flex-col"><div className="flex items-center justify-between"><Brand/>{onClose&&<button onClick={onClose}><X/></button>}</div><nav className="mt-7 space-y-1 overflow-y-auto">{items.map(([id,label,Icon])=><button key={id} onClick={()=>{setView(id);onClose?.()}} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-bold transition ${view===id?'bg-emerald-500 text-slate-950':'text-slate-400 hover:bg-slate-900 hover:text-white'}`}><Icon className="w-4 h-4"/>{label}</button>)}</nav><div className="mt-auto pt-4 border-t border-slate-800"><div className="text-xs text-slate-500 truncate">{user?.name||'Profissional'}</div><button onClick={async()=>{await api('/auth/logout',{method:'POST'}).catch(()=>{});location.assign('/login')}} className="mt-2 flex items-center gap-2 text-sm font-bold text-slate-300"><LogOut className="w-4 h-4"/> Sair</button></div></aside>}

function Dashboard({patients,dash,setView}:{patients:any[],dash:any,setView:(v:View)=>void}){const appts=dash?.appointments||[];return <><div className="flex items-end justify-between gap-4"><div><div className="text-sm font-bold text-emerald-600">Visão clínica</div><h1 className="text-3xl font-black tracking-tight">Seu consultório em tempo real</h1></div><button onClick={()=>setView('patients')} className="hidden sm:flex items-center gap-2 px-4 py-3 rounded-2xl bg-slate-950 text-white text-sm font-bold"><Users className="w-4 h-4"/> Pacientes</button></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-6"><Stat title="Pacientes" value={patients.length} sub="cadastrados" icon={Users}/><Stat title="Consultas" value={appts.length} sub="na agenda" icon={CalendarDays}/><Stat title="Receita" value={dash?.finance_summary?.revenue?`R$ ${Number(dash.finance_summary.revenue).toLocaleString('pt-BR')}`:'—'} sub="período atual" icon={TrendingUp}/><Stat title="IA clínica" value="Ativa" sub="copiloto disponível" icon={Bot}/></div><div className="grid xl:grid-cols-3 gap-5 mt-5"><div className="xl:col-span-2 rounded-3xl bg-white border border-slate-200 p-5"><div className="flex justify-between items-center"><h2 className="font-black text-lg">Pacientes recentes</h2><button onClick={()=>setView('patients')} className="text-sm font-bold text-emerald-600">Ver todos</button></div><div className="mt-4 divide-y divide-slate-100">{patients.slice(0,5).map(p=><div key={p.id} className="py-3 flex items-center gap-3"><div className="h-10 w-10 rounded-2xl bg-emerald-50 text-emerald-700 grid place-items-center font-black">{String(p.name||'P')[0]}</div><div className="flex-1"><div className="font-bold">{p.name}</div><div className="text-xs text-slate-500">{p.identifier||p.phone||'Paciente NutriOS'}</div></div><ChevronRight className="w-4 h-4 text-slate-300"/></div>)}{!patients.length&&<div className="py-10 text-center text-slate-400">Nenhum paciente cadastrado.</div>}</div></div><div className="rounded-3xl bg-slate-950 text-white p-5"><Sparkles className="text-emerald-400"/><h2 className="text-xl font-black mt-4">Copiloto clínico</h2><p className="text-sm text-slate-400 mt-2">A IA do NutriOS usa o contexto clínico do paciente para apoiar sua análise.</p><button onClick={()=>setView('patients')} className="mt-6 w-full py-3 rounded-2xl bg-emerald-500 text-slate-950 font-black">Selecionar paciente</button></div></div></>}

function Patients({rows,reload}:{rows:any[],reload:()=>void}){const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [name,setName]=useState('');const [email,setEmail]=useState('');const filtered=useMemo(()=>rows.filter(x=>String(x.name||'').toLowerCase().includes(q.toLowerCase())),[rows,q]);async function save(){if(!name.trim())return;await api('/app/api/pacientes',{method:'POST',body:JSON.stringify({name:name.trim(),identifier:email||null,plan_name:'Acompanhamento',duration_days:30,message_limit:200})});setOpen(false);setName('');setEmail('');reload()}return <><div className="flex flex-wrap gap-3 justify-between"><div><div className="text-sm font-bold text-emerald-600">Gestão clínica</div><h1 className="text-3xl font-black">Pacientes</h1></div><button onClick={()=>setOpen(true)} className="px-4 py-3 rounded-2xl bg-emerald-500 font-black">+ Novo paciente</button></div><div className="mt-6 rounded-3xl bg-white border border-slate-200 overflow-hidden"><div className="p-4 border-b border-slate-100"><div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar paciente" className="w-full rounded-xl border border-slate-200 pl-10 pr-3 py-2.5"/></div></div><div className="divide-y divide-slate-100">{filtered.map(p=><div key={p.id} className="p-4 flex items-center gap-4"><div className="h-11 w-11 rounded-2xl bg-emerald-50 grid place-items-center font-black text-emerald-700">{String(p.name||'P')[0]}</div><div className="flex-1"><div className="font-black">{p.name}</div><div className="text-xs text-slate-500">{p.identifier||p.phone||'Sem contato informado'}</div></div><span className={`text-[11px] font-bold px-2 py-1 rounded-full ${p.active!==false?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{p.active!==false?'Ativo':'Inativo'}</span></div>)}</div></div>{open&&<div className="fixed inset-0 bg-black/50 z-50 grid place-items-center p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Novo paciente</h2><button onClick={()=>setOpen(false)}><X/></button></div><div className="mt-5 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo" className="w-full border rounded-xl px-4 py-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail / identificador" className="w-full border rounded-xl px-4 py-3"/><button onClick={save} className="w-full rounded-xl bg-emerald-500 py-3 font-black">Cadastrar</button></div></div></div>}</>}

function Generic({title,desc,icon:Icon,children}:{title:string,desc:string,icon:any,children?:any}){return <><div className="flex items-center gap-4"><div className="h-12 w-12 rounded-2xl bg-emerald-50 text-emerald-600 grid place-items-center"><Icon/></div><div><h1 className="text-3xl font-black">{title}</h1><p className="text-sm text-slate-500 mt-1">{desc}</p></div></div><div className="mt-6">{children||<div className="rounded-3xl bg-white border border-slate-200 p-8 text-center text-slate-500">Módulo conectado ao backend do NutriOS.</div>}</div></>}
function FoodSearch(){const [q,setQ]=useState('');const [rows,setRows]=useState<any[]>([]);async function go(){setRows(await api(`/app/api/alimentos?q=${encodeURIComponent(q)}`).catch(()=>[]))}return <Generic title="Base de alimentos" desc="Pesquisa nutricional conectada à API do NutriOS." icon={Database}><div className="rounded-3xl bg-white border p-5"><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()} className="flex-1 border rounded-xl px-4 py-3" placeholder="Ex.: arroz, frango, banana"/><button onClick={go} className="px-5 rounded-xl bg-emerald-500 font-black">Buscar</button></div><div className="mt-4 divide-y">{rows.slice(0,20).map((x,i)=><div key={x.id||i} className="py-3 flex justify-between gap-4"><div className="font-bold">{x.nome||x.name}</div><div className="text-sm text-slate-500">{x.kcal||x.calories||'—'} kcal</div></div>)}</div></div></Generic>}

function Admin(){const [data,setData]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{api('/admin/api/dashboard').then(setData).catch((e:any)=>{if(e.status===401)location.assign('/login');else setError(e.message)})},[]);if(!data&&!error)return <Spinner/>;return <div className="min-h-screen bg-slate-100"><header className="bg-slate-950 text-white px-6 py-5"><div className="max-w-7xl mx-auto flex justify-between items-center"><Brand/><div className="flex items-center gap-3"><span className="hidden sm:inline text-sm text-slate-400">Admin mestre</span><Crown className="text-amber-400"/></div></div></header><main className="max-w-7xl mx-auto p-6"><div className="flex justify-between items-end"><div><div className="text-amber-600 text-sm font-black">SUPER ADMIN</div><h1 className="text-3xl font-black">Operação do SaaS</h1></div><button onClick={()=>location.assign('/app')} className="px-4 py-2 rounded-xl bg-white border font-bold">Ir para clínica</button></div>{error?<div className="mt-6 text-red-600">{error}</div>:<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-6"><Stat title="Clientes" value={data?.metrics?.clients_total??data?.clients?.length??0} icon={Users}/><Stat title="Ativos" value={data?.metrics?.clients_active??'—'} icon={ShieldCheck}/><Stat title="Pacientes" value={data?.metrics?.patients_total??'—'} icon={HeartPulse}/><Stat title="Receita" value={data?.metrics?.revenue?`R$ ${Number(data.metrics.revenue).toLocaleString('pt-BR')}`:'—'} icon={Wallet}/></div><div className="mt-5 rounded-3xl bg-white border p-5"><h2 className="font-black text-lg">Contas profissionais</h2><div className="mt-4 divide-y">{(data?.clients||[]).slice(0,15).map((c:any)=><div key={c.id} className="py-3 flex justify-between gap-3"><div><div className="font-bold">{c.name||c.identifier}</div><div className="text-xs text-slate-500">{c.identifier}</div></div><div className="text-xs font-bold text-emerald-700">{c.active!==false?'ATIVO':'INATIVO'}</div></div>)}</div></div></>}</main></div>}

function PatientPortal(){const [me,setMe]=useState<any>(null);const [plan,setPlan]=useState<any>(null);const [workout,setWorkout]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{Promise.all([api('/paciente/api/me'),api('/paciente/api/plano').catch(()=>null),api('/paciente/api/treino').catch(()=>null)]).then(([m,p,w])=>{setMe(m);setPlan(p);setWorkout(w)}).catch((e:any)=>{if(e.status===401)location.assign('/paciente/login');else setError(e.message)})},[]);if(!me&&!error)return <Spinner/>;return <div className="min-h-screen bg-slate-100"><header className="bg-slate-950 text-white p-5"><div className="max-w-5xl mx-auto flex justify-between items-center"><Brand/><button onClick={async()=>{await api('/paciente/auth/logout',{method:'POST'}).catch(()=>{});location.assign('/paciente/login')}}><LogOut/></button></div></header><main className="max-w-5xl mx-auto p-6"><div className="rounded-[2rem] bg-gradient-to-br from-slate-950 to-emerald-950 text-white p-7"><div className="text-sm text-emerald-300 font-bold">PORTAL DO PACIENTE</div><h1 className="text-3xl font-black mt-2">Olá, {me?.name||'Paciente'}</h1><p className="text-slate-400 mt-1">Seu acompanhamento nutricional em um só lugar.</p></div>{error&&<div className="mt-5 text-red-600">{error}</div>}<div className="grid lg:grid-cols-2 gap-5 mt-5"><div className="rounded-3xl bg-white border p-5"><div className="flex gap-3 items-center"><UtensilsCrossed className="text-emerald-600"/><h2 className="font-black text-lg">Plano alimentar</h2></div>{plan?<div className="mt-4"><div className="font-bold">{plan.title||'Plano atual'}</div><div className="text-sm text-slate-500 mt-2">Seu plano está disponível e conectado ao acompanhamento do profissional.</div></div>:<div className="mt-4 text-sm text-slate-500">Nenhum plano liberado ainda.</div>}</div><div className="rounded-3xl bg-white border p-5"><div className="flex gap-3 items-center"><Dumbbell className="text-emerald-600"/><h2 className="font-black text-lg">Treino</h2></div>{workout?.plan?<div className="mt-4 font-bold">{workout.plan.title||'Treino atual'}</div>:<div className="mt-4 text-sm text-slate-500">Nenhum treino publicado.</div>}</div></div></main></div>}

export default function App(){
  const path=location.pathname.replace(/\/$/,'')||'/';
  if(path==='/') return <Landing/>;
  if(path==='/login') return <Login/>;
  if(path==='/paciente/login') return <Login patient/>;
  if(path.startsWith('/admin')) return <Admin/>;
  if(path.startsWith('/paciente')) return <PatientPortal/>;
  return <Clinic/>;
}

function Clinic(){
  const [user,setUser]=useState<any>(null);const [patients,setPatients]=useState<any[]>([]);const [dash,setDash]=useState<any>(null);const [view,setViewState]=useState<View>(pathToView[location.pathname]||'dashboard');const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [mobile,setMobile]=useState(false);
  const setView=(v:View)=>{setViewState(v);history.pushState({},'',viewPath[v])};
  const load=async()=>{setBusy(true);setError('');try{const me=await api('/api/me');setUser(me);const [p,d]=await Promise.all([api<any[]>('/app/api/pacientes'),api('/app/api/dashboard-clinico').catch(()=>null)]);setPatients(p);setDash(d)}catch(e:any){if(e.status===401){location.assign('/login');return}setError(e.message||'Falha ao carregar')}finally{setBusy(false)}};
  useEffect(()=>{load();const pop=()=>setViewState(pathToView[location.pathname]||'dashboard');addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
  if(busy)return <Spinner/>;
  if(error)return <div className="min-h-screen bg-slate-950 text-white grid place-items-center p-6"><div className="text-center"><h1 className="text-2xl font-black">Não foi possível carregar</h1><p className="text-slate-400 mt-2">{error}</p><button onClick={load} className="mt-5 px-5 py-3 rounded-2xl bg-emerald-500 text-slate-950 font-black inline-flex gap-2"><RefreshCcw className="w-4 h-4"/> Tentar novamente</button></div></div>;
  return <div className="min-h-screen bg-slate-100 text-slate-900"><div className="hidden lg:block fixed inset-y-0 left-0 w-64"><Sidebar view={view} setView={setView} user={user}/></div>{mobile&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-black/50" onClick={()=>setMobile(false)}/><div className="relative w-72 h-full"><Sidebar view={view} setView={setView} user={user} onClose={()=>setMobile(false)}/></div></div>}<header className="lg:ml-64 h-16 bg-white border-b border-slate-200 px-4 lg:px-8 flex items-center justify-between sticky top-0 z-30"><button onClick={()=>setMobile(true)} className="lg:hidden"><Menu/></button><div className="hidden sm:flex items-center gap-2 text-sm text-slate-500"><ShieldCheck className="w-4 h-4 text-emerald-500"/> Ambiente clínico protegido</div><div className="flex items-center gap-3"><button className="h-9 w-9 rounded-xl bg-emerald-50 text-emerald-600 grid place-items-center"><Sparkles className="w-4 h-4"/></button><div className="text-right hidden sm:block"><div className="text-sm font-black">{user?.name||'Nutricionista'}</div><div className="text-[11px] text-slate-400">{user?.identifier||''}</div></div></div></header><main className="lg:ml-64 p-4 sm:p-6 lg:p-8 max-w-[1600px]">{view==='dashboard'&&<Dashboard patients={patients} dash={dash} setView={setView}/>} {view==='patients'&&<Patients rows={patients} reload={load}/>} {view==='meal'&&<Generic title="Plano alimentar" desc="Criação e gestão de planos nutricionais conectados aos pacientes." icon={UtensilsCrossed}/>} {view==='workout'&&<Generic title="Treinos" desc="Prescrição opcional de exercícios e acompanhamento." icon={Dumbbell}/>} {view==='metabolic'&&<Generic title="Cálculo metabólico" desc="Estimativas energéticas para apoiar a prescrição." icon={Calculator}/>} {view==='anthropometry'&&<Generic title="Análise corporal" desc="Antropometria, evolução e visualização clínica." icon={Scale}/>} {view==='phyto'&&<Generic title="Fitoterapia" desc="Prescrição e histórico fitoterápico do paciente." icon={Leaf}/>} {view==='labs'&&<Generic title="Exames laboratoriais" desc="Registro e leitura longitudinal de biomarcadores." icon={FlaskConical}/>} {view==='foods'&&<FoodSearch/>} {view==='appointments'&&<Generic title="Agenda" desc="Consultas e compromissos clínicos." icon={CalendarDays}/>} {view==='financial'&&<Generic title="Financeiro" desc="Receitas, pagamentos e visão financeira do consultório." icon={Wallet}/>}</main></div>
}
